version: '2'
services:
    pocjedibckgateway-app:
        image: pocjedibckgateway
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://pocjedibckgateway-mysql:3306/pocjedibckgateway?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=pocjedibckgateway-elasticsearch:9300
        ports:
            - 8888:8888
    pocjedibckgateway-mysql:
        extends:
            file: mysql.yml
            service: pocjedibckgateway-mysql
    pocjedibckgateway-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: pocjedibckgateway-elasticsearch
